//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int bookid { get; set; }
        public Nullable<int> staffid { get; set; }
        public Nullable<int> cusid { get; set; }
        public Nullable<int> roomid { get; set; }
        public Nullable<int> serdetailid { get; set; }
        public string booktype { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public Nullable<int> totalhours { get; set; }
        public string bookstatus { get; set; }
        public Nullable<decimal> payamount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
        public virtual ServiceOrder ServiceOrder { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
