//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryService
    {
        public int ID { get; set; }
        public Nullable<int> historyID { get; set; }
        public string sername { get; set; }
        public Nullable<int> serquantity { get; set; }
        public Nullable<decimal> sertotal { get; set; }
        public Nullable<decimal> seramount { get; set; }
    
        public virtual History History { get; set; }
    }
}
