//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payid { get; set; }
        public Nullable<int> bookid { get; set; }
        public Nullable<int> serid { get; set; }
        public Nullable<System.DateTime> paydate { get; set; }
        public Nullable<decimal> payamount { get; set; }
        public string paymethod { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Service Service { get; set; }
    }
}
